import { MigrationInterface, QueryRunner } from "typeorm";

export class AddMediaTables1772807249937 implements MigrationInterface {
    name = 'AddMediaTables1772807249937'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sermons" DROP CONSTRAINT "sermons_churchId_fkey"`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP CONSTRAINT "sermons_createdByUserId_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_churchId_fkey"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP CONSTRAINT "brand_themes_churchId_fkey"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP CONSTRAINT "brand_themes_defaultTemplatePackId_fkey"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" DROP CONSTRAINT "slide_templates_packId_fkey"`);
        await queryRunner.query(`ALTER TABLE "slides" DROP CONSTRAINT "slides_deckId_fkey"`);
        await queryRunner.query(`ALTER TABLE "slides" DROP CONSTRAINT "slides_templateId_fkey"`);
        await queryRunner.query(`ALTER TABLE "exports" DROP CONSTRAINT "exports_deckId_fkey"`);
        await queryRunner.query(`ALTER TABLE "decks" DROP CONSTRAINT "decks_churchId_fkey"`);
        await queryRunner.query(`ALTER TABLE "decks" DROP CONSTRAINT "decks_sermonId_fkey"`);
        await queryRunner.query(`ALTER TABLE "decks" DROP CONSTRAINT "decks_templatePackId_fkey"`);
        await queryRunner.query(`ALTER TABLE "decks" DROP CONSTRAINT "decks_themeId_fkey"`);
        await queryRunner.query(`CREATE TYPE "public"."audio_media_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "audio_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sermonId" uuid, "workspaceId" character varying, "text" text NOT NULL, "voiceId" character varying, "provider" character varying NOT NULL DEFAULT 'elevenlabs', "status" "public"."audio_media_status_enum" NOT NULL DEFAULT 'pending', "filePath" character varying, "durationSeconds" integer, "errorMessage" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7bc8bad1b6437020e5a3ff7bb56" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."music_media_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "music_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sermonId" uuid, "workspaceId" character varying, "prompt" text NOT NULL, "genre" character varying, "durationSeconds" integer, "provider" character varying NOT NULL DEFAULT 'suno', "status" "public"."music_media_status_enum" NOT NULL DEFAULT 'pending', "filePath" character varying, "errorMessage" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6c1959d6ff08910de756446a1a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."video_media_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "video_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deckId" uuid, "audioId" uuid, "sermonId" uuid, "workspaceId" character varying, "status" "public"."video_media_status_enum" NOT NULL DEFAULT 'pending', "filePath" character varying, "durationSeconds" integer, "resolution" character varying NOT NULL DEFAULT '1920x1080', "errorMessage" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2db879ed42e3308fe65e6796729" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "workspaceId" character varying`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "source" character varying NOT NULL DEFAULT 'slides_app'`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "seriesTitle"`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "seriesTitle" character varying`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "mainScriptureRef"`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "mainScriptureRef" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."sermon_tone" RENAME TO "sermon_tone_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sermons_tone_enum" AS ENUM('hopeful', 'urgent', 'reflective', 'challenging', 'encouraging')`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "tone" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "tone" TYPE "public"."sermons_tone_enum" USING "tone"::"text"::"public"."sermons_tone_enum"`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "tone" SET DEFAULT 'encouraging'`);
        await queryRunner.query(`DROP TYPE "public"."sermon_tone_old"`);
        await queryRunner.query(`ALTER TYPE "public"."cta_style" RENAME TO "cta_style_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sermons_ctastyle_enum" AS ENUM('salvation', 'prayer', 'discipleship', 'invitation', 'none')`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "ctaStyle" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "ctaStyle" TYPE "public"."sermons_ctastyle_enum" USING "ctaStyle"::"text"::"public"."sermons_ctastyle_enum"`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "ctaStyle" SET DEFAULT 'prayer'`);
        await queryRunner.query(`DROP TYPE "public"."cta_style_old"`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "passwordHash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "passwordHash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'pastor', 'editor')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'pastor'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "logoUrl"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "logoUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "primaryColor"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "primaryColor" character varying`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "secondaryColor"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "secondaryColor" character varying`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "backgroundStyle"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "backgroundStyle" character varying`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "fontHeading"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "fontHeading" character varying`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "fontBody"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "fontBody" character varying`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "defaultTemplatePackId"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "defaultTemplatePackId" character varying`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "churches" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "churches" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "churches" DROP COLUMN "timezone"`);
        await queryRunner.query(`ALTER TABLE "churches" ADD "timezone" character varying`);
        await queryRunner.query(`ALTER TABLE "churches" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "churches" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "slide_templates" DROP COLUMN "packId"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ADD "packId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "slide_templates" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "slide_templates" DROP COLUMN "layoutKey"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ADD "layoutKey" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."slide_type" RENAME TO "slide_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."slide_templates_slidetype_enum" AS ENUM('title', 'scripture', 'point', 'support', 'transition', 'application', 'prayer', 'invitation', 'announcement')`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ALTER COLUMN "slideType" TYPE "public"."slide_templates_slidetype_enum" USING "slideType"::"text"::"public"."slide_templates_slidetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."slide_type_old"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "slide_templates" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."slide_type" RENAME TO "slide_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."slides_type_enum" AS ENUM('title', 'scripture', 'point', 'support', 'transition', 'application', 'prayer', 'invitation', 'announcement')`);
        await queryRunner.query(`ALTER TABLE "slides" ALTER COLUMN "type" TYPE "public"."slides_type_enum" USING "type"::"text"::"public"."slides_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."slide_type_old"`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "layoutKey"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "layoutKey" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "imagePrompt"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "imagePrompt" character varying`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "contentImagePrompt"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "contentImagePrompt" character varying`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "imageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "imageProvider"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "imageProvider" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."slide_image_status" RENAME TO "slide_image_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."slides_imagestatus_enum" AS ENUM('pending', 'ready', 'failed')`);
        await queryRunner.query(`ALTER TABLE "slides" ALTER COLUMN "imageStatus" TYPE "public"."slides_imagestatus_enum" USING "imageStatus"::"text"::"public"."slides_imagestatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."slide_image_status_old"`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "contentImageUrl"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "contentImageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "contentImageProvider"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "contentImageProvider" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."slide_image_status" RENAME TO "slide_image_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."slides_contentimagestatus_enum" AS ENUM('pending', 'ready', 'failed')`);
        await queryRunner.query(`ALTER TABLE "slides" ALTER COLUMN "contentImageStatus" TYPE "public"."slides_contentimagestatus_enum" USING "contentImageStatus"::"text"::"public"."slides_contentimagestatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."slide_image_status_old"`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."export_type" RENAME TO "export_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."exports_type_enum" AS ENUM('pptx', 'pdf')`);
        await queryRunner.query(`ALTER TABLE "exports" ALTER COLUMN "type" TYPE "public"."exports_type_enum" USING "type"::"text"::"public"."exports_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."export_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."export_status" RENAME TO "export_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."exports_status_enum" AS ENUM('queued', 'rendering', 'ready', 'failed')`);
        await queryRunner.query(`ALTER TABLE "exports" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "exports" ALTER COLUMN "status" TYPE "public"."exports_status_enum" USING "status"::"text"::"public"."exports_status_enum"`);
        await queryRunner.query(`ALTER TABLE "exports" ALTER COLUMN "status" SET DEFAULT 'queued'`);
        await queryRunner.query(`DROP TYPE "public"."export_status_old"`);
        await queryRunner.query(`ALTER TABLE "exports" DROP COLUMN "fileUrl"`);
        await queryRunner.query(`ALTER TABLE "exports" ADD "fileUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "exports" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "exports" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."deck_status" RENAME TO "deck_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."decks_status_enum" AS ENUM('draft', 'generating', 'ready', 'exporting', 'exported', 'failed')`);
        await queryRunner.query(`ALTER TABLE "decks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "decks" ALTER COLUMN "status" TYPE "public"."decks_status_enum" USING "status"::"text"::"public"."decks_status_enum"`);
        await queryRunner.query(`ALTER TABLE "decks" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."deck_status_old"`);
        await queryRunner.query(`ALTER TABLE "decks" DROP COLUMN "generationProvider"`);
        await queryRunner.query(`ALTER TABLE "decks" ADD "generationProvider" character varying`);
        await queryRunner.query(`ALTER TABLE "decks" DROP COLUMN "generationModel"`);
        await queryRunner.query(`ALTER TABLE "decks" ADD "generationModel" character varying`);
        await queryRunner.query(`ALTER TABLE "decks" DROP COLUMN "templatePackId"`);
        await queryRunner.query(`ALTER TABLE "decks" ADD "templatePackId" character varying`);
        await queryRunner.query(`ALTER TABLE "decks" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "decks" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "decks" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "decks" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "template_packs" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "template_packs" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "template_packs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "template_packs" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "template_packs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "template_packs" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "template_packs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "template_packs" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audio_media" ADD CONSTRAINT "FK_a290ac9ea404864d40e7aeede8c" FOREIGN KEY ("sermonId") REFERENCES "sermons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "music_media" ADD CONSTRAINT "FK_c6a8226fc281075b9e9f1470040" FOREIGN KEY ("sermonId") REFERENCES "sermons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD CONSTRAINT "FK_0e2bfa142a109686903f638604d" FOREIGN KEY ("churchId") REFERENCES "churches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD CONSTRAINT "FK_65721b9dbe222be8bb2b2748f42" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_3ad405e3bd92680e4792ac50880" FOREIGN KEY ("churchId") REFERENCES "churches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD CONSTRAINT "FK_c25761ac05f08db085eba88e64a" FOREIGN KEY ("churchId") REFERENCES "churches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "slides" ADD CONSTRAINT "FK_5665b1946bfc5be358f40590bc0" FOREIGN KEY ("deckId") REFERENCES "decks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "slides" ADD CONSTRAINT "FK_9a182dbe0fe4f50154de5e95ec2" FOREIGN KEY ("templateId") REFERENCES "slide_templates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exports" ADD CONSTRAINT "FK_27ff2d49258bf7744fb1ae8faba" FOREIGN KEY ("deckId") REFERENCES "decks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decks" ADD CONSTRAINT "FK_5fc562fe71d9ce2b43989418ac3" FOREIGN KEY ("churchId") REFERENCES "churches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decks" ADD CONSTRAINT "FK_c5a1368cb33885a716afa524bb5" FOREIGN KEY ("sermonId") REFERENCES "sermons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decks" ADD CONSTRAINT "FK_295bb15831fa96d5bb8fa27253f" FOREIGN KEY ("themeId") REFERENCES "brand_themes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video_media" ADD CONSTRAINT "FK_f2cefc6fda16069cc713f9ec784" FOREIGN KEY ("deckId") REFERENCES "decks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video_media" ADD CONSTRAINT "FK_dea19a298571dfd9981090171f9" FOREIGN KEY ("audioId") REFERENCES "audio_media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video_media" ADD CONSTRAINT "FK_9a70e680815e0b783e9b1d41e31" FOREIGN KEY ("sermonId") REFERENCES "sermons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "video_media" DROP CONSTRAINT "FK_9a70e680815e0b783e9b1d41e31"`);
        await queryRunner.query(`ALTER TABLE "video_media" DROP CONSTRAINT "FK_dea19a298571dfd9981090171f9"`);
        await queryRunner.query(`ALTER TABLE "video_media" DROP CONSTRAINT "FK_f2cefc6fda16069cc713f9ec784"`);
        await queryRunner.query(`ALTER TABLE "decks" DROP CONSTRAINT "FK_295bb15831fa96d5bb8fa27253f"`);
        await queryRunner.query(`ALTER TABLE "decks" DROP CONSTRAINT "FK_c5a1368cb33885a716afa524bb5"`);
        await queryRunner.query(`ALTER TABLE "decks" DROP CONSTRAINT "FK_5fc562fe71d9ce2b43989418ac3"`);
        await queryRunner.query(`ALTER TABLE "exports" DROP CONSTRAINT "FK_27ff2d49258bf7744fb1ae8faba"`);
        await queryRunner.query(`ALTER TABLE "slides" DROP CONSTRAINT "FK_9a182dbe0fe4f50154de5e95ec2"`);
        await queryRunner.query(`ALTER TABLE "slides" DROP CONSTRAINT "FK_5665b1946bfc5be358f40590bc0"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP CONSTRAINT "FK_c25761ac05f08db085eba88e64a"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_3ad405e3bd92680e4792ac50880"`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP CONSTRAINT "FK_65721b9dbe222be8bb2b2748f42"`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP CONSTRAINT "FK_0e2bfa142a109686903f638604d"`);
        await queryRunner.query(`ALTER TABLE "music_media" DROP CONSTRAINT "FK_c6a8226fc281075b9e9f1470040"`);
        await queryRunner.query(`ALTER TABLE "audio_media" DROP CONSTRAINT "FK_a290ac9ea404864d40e7aeede8c"`);
        await queryRunner.query(`ALTER TABLE "template_packs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "template_packs" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "template_packs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "template_packs" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "template_packs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "template_packs" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "template_packs" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "template_packs" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "decks" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "decks" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "decks" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "decks" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "decks" DROP COLUMN "templatePackId"`);
        await queryRunner.query(`ALTER TABLE "decks" ADD "templatePackId" uuid`);
        await queryRunner.query(`ALTER TABLE "decks" DROP COLUMN "generationModel"`);
        await queryRunner.query(`ALTER TABLE "decks" ADD "generationModel" text`);
        await queryRunner.query(`ALTER TABLE "decks" DROP COLUMN "generationProvider"`);
        await queryRunner.query(`ALTER TABLE "decks" ADD "generationProvider" text`);
        await queryRunner.query(`CREATE TYPE "public"."deck_status_old" AS ENUM('draft', 'generating', 'ready', 'exporting', 'exported', 'failed')`);
        await queryRunner.query(`ALTER TABLE "decks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "decks" ALTER COLUMN "status" TYPE "public"."deck_status_old" USING "status"::"text"::"public"."deck_status_old"`);
        await queryRunner.query(`ALTER TABLE "decks" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."decks_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."deck_status_old" RENAME TO "deck_status"`);
        await queryRunner.query(`ALTER TABLE "exports" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "exports" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "exports" DROP COLUMN "fileUrl"`);
        await queryRunner.query(`ALTER TABLE "exports" ADD "fileUrl" text`);
        await queryRunner.query(`CREATE TYPE "public"."export_status_old" AS ENUM('queued', 'rendering', 'ready', 'failed')`);
        await queryRunner.query(`ALTER TABLE "exports" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "exports" ALTER COLUMN "status" TYPE "public"."export_status_old" USING "status"::"text"::"public"."export_status_old"`);
        await queryRunner.query(`ALTER TABLE "exports" ALTER COLUMN "status" SET DEFAULT 'queued'`);
        await queryRunner.query(`DROP TYPE "public"."exports_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."export_status_old" RENAME TO "export_status"`);
        await queryRunner.query(`CREATE TYPE "public"."export_type_old" AS ENUM('pptx', 'pdf')`);
        await queryRunner.query(`ALTER TABLE "exports" ALTER COLUMN "type" TYPE "public"."export_type_old" USING "type"::"text"::"public"."export_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."exports_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."export_type_old" RENAME TO "export_type"`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."slide_image_status_old" AS ENUM('pending', 'ready', 'failed')`);
        await queryRunner.query(`ALTER TABLE "slides" ALTER COLUMN "contentImageStatus" TYPE "public"."slide_image_status_old" USING "contentImageStatus"::"text"::"public"."slide_image_status_old"`);
        await queryRunner.query(`DROP TYPE "public"."slides_contentimagestatus_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."slide_image_status_old" RENAME TO "slide_image_status"`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "contentImageProvider"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "contentImageProvider" text`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "contentImageUrl"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "contentImageUrl" text`);
        await queryRunner.query(`CREATE TYPE "public"."slide_image_status_old" AS ENUM('pending', 'ready', 'failed')`);
        await queryRunner.query(`ALTER TABLE "slides" ALTER COLUMN "imageStatus" TYPE "public"."slide_image_status_old" USING "imageStatus"::"text"::"public"."slide_image_status_old"`);
        await queryRunner.query(`DROP TYPE "public"."slides_imagestatus_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."slide_image_status_old" RENAME TO "slide_image_status"`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "imageProvider"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "imageProvider" text`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "imageUrl" text`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "contentImagePrompt"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "contentImagePrompt" text`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "imagePrompt"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "imagePrompt" text`);
        await queryRunner.query(`ALTER TABLE "slides" DROP COLUMN "layoutKey"`);
        await queryRunner.query(`ALTER TABLE "slides" ADD "layoutKey" text NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."slide_type_old" AS ENUM('title', 'scripture', 'point', 'support', 'transition', 'application', 'prayer', 'invitation', 'announcement')`);
        await queryRunner.query(`ALTER TABLE "slides" ALTER COLUMN "type" TYPE "public"."slide_type_old" USING "type"::"text"::"public"."slide_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."slides_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."slide_type_old" RENAME TO "slide_type"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "slide_templates" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."slide_type_old" AS ENUM('title', 'scripture', 'point', 'support', 'transition', 'application', 'prayer', 'invitation', 'announcement')`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ALTER COLUMN "slideType" TYPE "public"."slide_type_old" USING "slideType"::"text"::"public"."slide_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."slide_templates_slidetype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."slide_type_old" RENAME TO "slide_type"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" DROP COLUMN "layoutKey"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ADD "layoutKey" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "slide_templates" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "slide_templates" DROP COLUMN "packId"`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ADD "packId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "churches" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "churches" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "churches" DROP COLUMN "timezone"`);
        await queryRunner.query(`ALTER TABLE "churches" ADD "timezone" text`);
        await queryRunner.query(`ALTER TABLE "churches" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "churches" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "defaultTemplatePackId"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "defaultTemplatePackId" uuid`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "fontBody"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "fontBody" text`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "fontHeading"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "fontHeading" text`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "backgroundStyle"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "backgroundStyle" text`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "secondaryColor"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "secondaryColor" text`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "primaryColor"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "primaryColor" text`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "logoUrl"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "logoUrl" text`);
        await queryRunner.query(`ALTER TABLE "brand_themes" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_old" AS ENUM('admin', 'pastor', 'editor')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_old" USING "role"::"text"::"public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'pastor'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "passwordHash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "passwordHash" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."cta_style_old" AS ENUM('salvation', 'prayer', 'discipleship', 'invitation', 'none')`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "ctaStyle" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "ctaStyle" TYPE "public"."cta_style_old" USING "ctaStyle"::"text"::"public"."cta_style_old"`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "ctaStyle" SET DEFAULT 'prayer'`);
        await queryRunner.query(`DROP TYPE "public"."sermons_ctastyle_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."cta_style_old" RENAME TO "cta_style"`);
        await queryRunner.query(`CREATE TYPE "public"."sermon_tone_old" AS ENUM('hopeful', 'urgent', 'reflective', 'challenging', 'encouraging')`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "tone" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "tone" TYPE "public"."sermon_tone_old" USING "tone"::"text"::"public"."sermon_tone_old"`);
        await queryRunner.query(`ALTER TABLE "sermons" ALTER COLUMN "tone" SET DEFAULT 'encouraging'`);
        await queryRunner.query(`DROP TYPE "public"."sermons_tone_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."sermon_tone_old" RENAME TO "sermon_tone"`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "mainScriptureRef"`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "mainScriptureRef" text`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "seriesTitle"`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "seriesTitle" text`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD "title" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "sermons" DROP COLUMN "workspaceId"`);
        await queryRunner.query(`DROP TABLE "video_media"`);
        await queryRunner.query(`DROP TYPE "public"."video_media_status_enum"`);
        await queryRunner.query(`DROP TABLE "music_media"`);
        await queryRunner.query(`DROP TYPE "public"."music_media_status_enum"`);
        await queryRunner.query(`DROP TABLE "audio_media"`);
        await queryRunner.query(`DROP TYPE "public"."audio_media_status_enum"`);
        await queryRunner.query(`ALTER TABLE "decks" ADD CONSTRAINT "decks_themeId_fkey" FOREIGN KEY ("themeId") REFERENCES "brand_themes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decks" ADD CONSTRAINT "decks_templatePackId_fkey" FOREIGN KEY ("templatePackId") REFERENCES "template_packs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decks" ADD CONSTRAINT "decks_sermonId_fkey" FOREIGN KEY ("sermonId") REFERENCES "sermons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "decks" ADD CONSTRAINT "decks_churchId_fkey" FOREIGN KEY ("churchId") REFERENCES "churches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exports" ADD CONSTRAINT "exports_deckId_fkey" FOREIGN KEY ("deckId") REFERENCES "decks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "slides" ADD CONSTRAINT "slides_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "slide_templates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "slides" ADD CONSTRAINT "slides_deckId_fkey" FOREIGN KEY ("deckId") REFERENCES "decks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "slide_templates" ADD CONSTRAINT "slide_templates_packId_fkey" FOREIGN KEY ("packId") REFERENCES "template_packs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD CONSTRAINT "brand_themes_defaultTemplatePackId_fkey" FOREIGN KEY ("defaultTemplatePackId") REFERENCES "template_packs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brand_themes" ADD CONSTRAINT "brand_themes_churchId_fkey" FOREIGN KEY ("churchId") REFERENCES "churches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_churchId_fkey" FOREIGN KEY ("churchId") REFERENCES "churches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD CONSTRAINT "sermons_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sermons" ADD CONSTRAINT "sermons_churchId_fkey" FOREIGN KEY ("churchId") REFERENCES "churches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
